# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://Chryzanthemum.github.io/xgb2sql/"

git_url = "https://github.com/Chryzanthemum/xgb2sql/tree/master/"

def custom_doc_links(name): return None
